**IMPORTING THE LIBARIES**

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [ ]:
tf.__version__

'2.13.0'

**DATA PREPROCESSING**

**IMPORTING THE DATASET**

In [ ]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


**SPLITTING THE DATASET INTO TRAINING AND TEST SET**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**FEATURE SCALING**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**BUILDING THE ANN**

**INITIALIZING THE ANN**

In [ ]:
ann = tf.keras.models.Sequential()


**ADDING THE INPUT LAYER AND THE FIRST HIDDEN LAYER**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**ADDING THE SECOND HIDDEN LAYER**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**ADDING THE OUTPUT LAYER**

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**TRAINING THE ANN**

**COMPILING THE ANN**

In [ ]:
ann.compile(optimizer = 'adam', loss ='binary_crossentropy', metrics = ['accuracy'])

**TRAINING THE ANN ON THE TRAINING SET**

In [ ]:
ann.fit(X_train, y_train, batch_size = 23, epochs = 120)

Epoch 1/120
14/14 [==============================] - 1s 3ms/step - loss: 0.6929 - accuracy: 0.3750
Epoch 2/120
14/14 [==============================] - 0s 2ms/step - loss: 0.6644 - accuracy: 0.4062
Epoch 3/120
14/14 [==============================] - 0s 2ms/step - loss: 0.6430 - accuracy: 0.4938
Epoch 4/120
14/14 [==============================] - 0s 2ms/step - loss: 0.6256 - accuracy: 0.6438
Epoch 5/120
14/14 [==============================] - 0s 2ms/step - loss: 0.6120 - accuracy: 0.7156
Epoch 6/120
14/14 [==============================] - 0s 2ms/step - loss: 0.5990 - accuracy: 0.7375
Epoch 7/120
14/14 [==============================] - 0s 2ms/step - loss: 0.5871 - accuracy: 0.7719
Epoch 8/120
14/14 [==============================] - 0s 2ms/step - loss: 0.5756 - accuracy: 0.8000
Epoch 9/120
14/14 [==============================] - 0s 2ms/step - loss: 0.5649 - accuracy: 0.8062
Epoch 10/120
14/14 [==============================] - 0s 2ms/step - loss: 0.5540 - accuracy: 0.8250
Epoch 11/

**PREDICTING THE TEST SET RESULT**

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

3/3 [==============================] - 0s 4ms/step
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


**MAKING THE CONFUSION MATRIX**

In [ ]:
from keras.src.metrics.accuracy_metrics import accuracy
from sklearn.metrics import confusion_matrix, accuracy_score
cm =confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[55  3]
 [ 1 21]]


0.95